import 'dotenv/config'; // load .env

export const KAFKA_TOPICS = {
  LEAVE_REQUEST_CREATED: process.env.KAFKA_LEAVE_REQUEST_CREATED || '',
  LEAVE_REQUEST_CREATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_CREATED_DLQ || '',
  LEAVE_REQUEST_UPDATED: process.env.KAFKA_LEAVE_REQUEST_UPDATED || '',
  LEAVE_REQUEST_UPDATED_DLQ: process.env.KAFKA_LEAVE_REQUEST_UPDATED_DLQ || '',
  LEAVE_REQUEST_STATUS_UPDATED:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED || '',
  LEAVE_REQUEST_STATUS_UPDATED_DLQ:
    process.env.KAFKA_LEAVE_REQUEST_STATUS_UPDATED_DLQ || '',
  USER_MENTIONED: process.env.KAFKA_USER_MENTIONED || '',
  USER_MENTIONED_DLQ: process.env.KAFKA_USER_MENTIONED_DLQ || '',
} as const;

export const KAFKA_DLQ_MAP: Record<string, string> = {
  [KAFKA_TOPICS.LEAVE_REQUEST_CREATED]: KAFKA_TOPICS.LEAVE_REQUEST_CREATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_UPDATED]: KAFKA_TOPICS.LEAVE_REQUEST_UPDATED_DLQ,
  [KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED]:
    KAFKA_TOPICS.LEAVE_REQUEST_STATUS_UPDATED_DLQ,
  [KAFKA_TOPICS.USER_MENTIONED]: KAFKA_TOPICS.USER_MENTIONED_DLQ,
};
